### PR TITLE
Count

### PR DESCRIPTION
**Pull request by nomizuno**

### CODE REVIEW

**Comment by nomizuno** [comment]
コンフリクトしてマージできないです！
いつも勝手に作成されてしまうファイルが原因のうようです。

**Comment by watsonso** [comment]
なるほろ
ちょっと確認するわ

**Comment by nomizuno** [comment]
bundle install もうまくできず、
なんか別のエラーも出るようになってしまいました。。
どこから手をつければよいでしょうか笑

**Comment by nomizuno** [comment]
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.0.0)

  In Gemfile:
    rails (= 5.0.0)

    quiet_assets was resolved to 1.0.0, which depends on
      rails (~> 3.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Bundler could not find compatible versions for gem "railties":
  In snapshot (Gemfile.lock):
    railties (= 5.0.0)

  In Gemfile:
    quiet_assets was resolved to 1.0.1, which depends on
      railties (~> 3.1)

    rails (= 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by nomizuno** [comment]
bundle installのコンフリクトはこのページで解決しました！
https://qiita.com/_kazuya/items/5376ab84ed870ceb5a3a

**Comment by nomizuno** [comment]
しかし
「gem 'quiet_assets', group: :development
を追加して bundle install 」するとい同様のエラーが出ます。

Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    rails (= 5.0.0) was resolved to 5.0.0, which depends on
      activemodel (= 5.0.0)

    web-console (~> 2.0) was resolved to 2.0.0, which depends on
      activemodel (~> 4.0)

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    jbuilder (~> 2.0) was resolved to 2.7.0, which depends on
      activesupport (>= 4.2.0)

    rails (= 5.0.0) was resolved to 5.0.0, which depends on
      activesupport (= 5.0.0)

    spring was resolved to 2.0.2, which depends on
      activesupport (>= 4.2)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 5.0.0)

    quiet_assets was resolved to 1.0.0, which depends on
      rails (~> 3.1)

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    jquery-rails was resolved to 4.3.1, which depends on
      railties (>= 4.2.0)

    quiet_assets was resolved to 1.1.0, which depends on
      railties (< 5.0, >= 3.1)

    rails (= 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0)

    rails-i18n (~> 5.0.0) was resolved to 5.0.4, which depends on
      railties (~> 5.0)

    sass-rails (~> 5.0) was resolved to 5.0.4, which depends on
      railties (< 5.0, >= 4.0.0)

    web-console (~> 2.0) was resolved to 2.3.0, which depends on
      railties (>= 4.0)

**Pull request closed without merging**
